import React from "react"
import { SectionWrapper } from "./SectionWrapper"
import { Project, type ProjectProps } from "../Project"

interface ProjectsProps {}

const projects: ProjectProps[] = [
    {
        name: "WhatsApp Business Management SaaS (Web and Meta API, Tenant-Isolated on GCE)",
        type: "professional",
        technologies: [
            "React.js",
            "Node.js (Express)",
            "Socket.IO",
            "MySQL",
            "Meta WhatsApp Cloud API",
            "wweb.js",
            "Docker",
            "Google Compute Engine",
            "Reverse Proxy",
        ],
        platforms: ["Web"],
        descriptionLines: [
            "WhatsApp operations for multi-number teams: shared inbox (WhatsApp Web–inspired), Kanban boards, bulk messaging, and chatbot automation.",
            "Role-based number assignment, conversation routing across boards/rooms, audit logging, and real-time monitoring via Socket.IO.",
            "Master control plane provisions a dedicated Google Compute Engine VM per customer; all HTTP/WebSocket traffic is reverse-proxied to the correct tenant.",
            "Each tenant VM runs a Dockerized stack (wweb.js driver, Meta Cloud API workers, Express API, MySQL) for isolation, stability, and zero noisy-neighbor interference.",
        ],
        highlights: [
            // Product features
            "Role-Based Number Assignment: Admins link WhatsApp numbers to users/departments and set permissions",
            "Conversational Workspace: WhatsApp Web-inspired inbox plus Kanban boards; move threads across columns/boards",
            "Chatbot Builder: Visual routing and replies; bots can hand off to rooms/boards based on scenario rules",
            "Bulk Messaging: Utility/promotional sends through Meta’s official platform, integrated with boards and bots",
            "Auditability: Every action is logged and queryable by administrators",
            // Control plane & isolation
            "Master API Orchestrator: Admin panel triggers per-customer provisioning on GCE (golden image + startup scripts) and registers routing/credentials",
            "Strong Tenant Isolation: One VM per customer; failures and spikes are contained. No cross-tenant impact",
            "Edge Proxy & WS Tunneling: Reverse proxy routes HTTPS and Socket.IO namespaces to the correct tenant VM with sticky sessions",
            "Per-Tenant Docker Stack: Containers for wweb.js (WhatsApp Web), Meta Cloud API workers, Express API, and a dedicated MySQL instance",
            "Data Separation: Distinct databases and secrets per tenant; optional automated backups/snapshots at the VM or DB level",
            // Tech notes
            "Stack: React (TypeScript) front end; Node.js (Express) + Socket.IO; Dockerized services on per-tenant GCE VMs; MySQL per tenant",
        ],
    },
    {
        name: "Blood Exam Data Processing Automation",
        type: "personal",
        technologies: ["Node.js", "TypeScript", "Excel Processing", "CSV Generation", "Medical Algorithms"],
        platforms: ["CLI Tool"],
        descriptionLines: [
            "A friend was struggling with manual processing of thousands of blood exam records from Excel files, requiring complex calculations, age filtering, and data normalization - a process prone to human error and time consumption.",
            "Developed an automated Node.js solution that processes multiple Excel files simultaneously, applies medical algorithms for creatinine clearance calculation, filters invalid records, and outputs standardized CSV reports with dynamic timestamping.",
            "The tool processes all Excel files in an input directory, automatically filters patients (18-100 age range), calculates medical metrics with gender-specific formulas, and generates audit-ready CSV reports in an output folder with processing statistics logged to console.",
        ],
        highlights: [
            "Automated processing pipeline: Excel ingestion → data validation → medical calculations → CSV output generation",
            "Implemented gender-specific creatinine clearance algorithms with precision handling (5 decimals)",
            "Developed intelligent age filtering (18-100) with detailed exclusion reporting",
            "Engineered dynamic field mapping to handle inconsistent Excel column structures",
            "Created automatic directory management with timestamped CSV outputs (./output/Result-{date}.csv)",
            "Designed batch processing for multiple files with Promise.all() optimization",
            "Built data normalization system handling comma/decimal conversions and NaN values",
        ],
    },
    {
        name: "Npm Library: Burgos Snackbar (Global Notification System)",
        type: "personal",
        technologies: ["React", "TypeScript", "Context API", "Material-UI", "Custom Hooks"],
        platforms: ["Web"],
        descriptionLines: [
            "React applications needed a simple yet powerful notification system that could display Material-UI snackbars from any component without prop drilling or complex state management.",
            "Created a solution combining Context API with Material-UI's Snackbar component, providing a provider component for app-wide access and a custom hook for triggering notifications with minimal code.",
            "Developers wrap their app with <SnackbarProvider>, place the <Snackbar /> component once, and trigger notifications from anywhere using snackbar({ severity: 'success', text: 'Message' }) from the useSnackbar hook.",
        ],
        highlights: [
            "Global Access: Context-based solution enabling snackbar triggers from any component",
            "Minimal Setup: Only requires wrapping app with SnackbarProvider and placing <Snackbar/> component once",
            "Simple API: useSnackbar hook provides snackbar() method accepting severity and text parameters",
            "Material-UI Integration: Leverages Material-UI's Snackbar component for consistent styling",
            "Type-Safe: Built with TypeScript for enhanced developer experience",
            "Lightweight: Single-file implementation with zero dependencies beyond React and Material-UI",
            "Declarative Usage: Clean JSX-free triggering via object parameters",
            "Customizable: Supports all Material-UI Snackbar props through options object",
        ],
    },
    {
        name: "PagSeguro API Challenge Decryption System",
        type: "personal",
        technologies: ["Python", "PyCryptodome", "RSA-OAEP", "Base64", "PagSeguro API"],
        platforms: ["CLI Tool"],
        descriptionLines: [
            "PagSeguro's API certificate creation requires solving cryptographic challenges that involve Base64 decoding, RSA-OAEP decryption, and proper HTTP challenge response handling - a complex manual process prone to errors.",
            "Developed an automated Python CLI tool that handles the entire challenge flow: key generation, Base64 decoding, RSA decryption using PKCS1_OAEP, and proper API response formatting with SHA256 hashing.",
            "Run via command line (with sandbox flag support), the script guides users through token input, automatically solves cryptographic challenges, handles key exchanges, and saves final certificates with client-specific configurations.",
        ],
        highlights: [
            "End-to-End Challenge Handling: Automates the full OAuth2 challenge flow from initiation to certificate storage",
            "Cryptographic Implementation: RSA-OAEP decryption with SHA256 hashing and Base64 decoding",
            "Environment Support: Sandbox/production toggle via --sandbox flag",
            "Key Management: Automatic generation and storage of public/private key pairs",
            "User Guidance: Interactive CLI prompts with validation instructions",
            "Certificate Generation: Creates client-specific JSON certificates with all required API credentials",
            "Error Handling: Structured exception handling for API failures and crypto operations",
            "PagSeguro API Integration: Handles all required headers (Authorization, X_CHALLENGE)",
        ],
    },
    {
        name: "Government Compliance Integration System",
        type: "professional",
        technologies: ["Python", "SQL Server", "MySQL", "REST API", "PyODBC"],
        platforms: ["Backend Service"],
        descriptionLines: [
            "Government regulations required real-time reporting of employee/visitor access events and credentialing status to the Portal Único Siscomex system, but manual reporting was error-prone and inefficient.",
            "Developed an automated Python service that continuously monitors SQL Server databases for new access events, processes them into government-compliant formats, and submits them via the Siscomex API while maintaining token authentication and handling contingencies.",
            "The service runs as a persistent daemon, checking for new entries/exits every second, processing them through the Receita integration module, and storing API responses in MySQL for auditing and reconciliation.",
        ],
        highlights: [
            "Real-time Event Processing: Monitors SQL Server for new access events (entries/exits) and processes them within seconds",
            "Government API Integration: Handles authentication (certificate-based) and data formatting for Siscomex Portal Único endpoints",
            "Employee Lifecycle Management: Automated credentialing (credenciamento) and resignation (demissao) reporting",
            "Visitor Tracking: Dedicated visitor processing with MySQL persistence",
            "Token Management: Automatic renewal of API tokens using client certificates",
            "Data Synchronization: Bi-directional sync between SQL Server (source) and MySQL (processed records)",
            "Error Handling: Comprehensive exception handling with detailed logging",
            "Configuration-Driven: Centralized config.json for databases, API URLs, and recinto codes",
        ],
    },
    {
        name: "Terminal-Based Real-Time Chat System",
        type: "personal",
        technologies: ["Python", "Pusher API", "WebSockets", "REST API", "Pysher", "Dotenv"],
        platforms: ["CLI"],
        descriptionLines: [
            "Friends needed a lightweight, real-time chat solution that could run directly in terminals without browser dependencies, but existing solutions required complex setups or graphical interfaces.",
            "Developed a Python CLI application using Pusher for real-time messaging, featuring user authentication, connection management, and color-coded message display - all within the terminal environment.",
            "Users run the script, enter their username, and immediately join the chatroom where they can send/receive messages in real-time. The system handles disconnections gracefully and broadcasts join/leave notifications.",
        ],
        highlights: [
            "Real-time Messaging: Implemented WebSocket communication via Pusher channels for instant message delivery",
            "Terminal UI: Designed clean CLI interface with color-coded messages (blue for users, green for system)",
            "User Management: Created connection tracking system with REST backend integration",
            "Session Handling: Automatic disconnection notifications on Ctrl+C interrupt",
            "Pusher Integration: Dual implementation using both Pusher HTTP library and Pysher client",
            "Environment Configuration: Dotenv support for secure credential management",
            "Multi-user Support: Concurrent chat participation with username identification",
            "Connection Callbacks: Implemented pusher:connection_established event handling",
        ],
    },
    {
        name: "Genetic Analysis PDF Data Extractor",
        type: "personal",
        technologies: ["Python", "PyPDF2", "Pandas", "Excel Automation", "Bioinformatics"],
        platforms: ["CLI Tool"],
        descriptionLines: [
            "Friend (genetic researcher) needed to extract structured data from FGENESH/Softberry PDF analysis reports containing ORF positions, scores, and base pair counts, but manual extraction was time-consuming and error-prone.",
            "Developed a Python script that automatically parses genetic analysis PDFs, identifies key markers like ORF positions, scores, and base pair counts using pattern recognition, and structures the data into organized Excel spreadsheets.",
            "Researchers place PDFs in the 'data/' folder and run the script, which processes all files, extracts genetic markers, handles multiple ORF conformations per sequence, and outputs the consolidated results to 'saida.xlsx' with color-coded terminal feedback.",
        ],
        highlights: [
            "PDF Pattern Recognition: Implements marker-based text extraction for genetic parameters (ORF positions, scores, pb counts)",
            "Multi-ORF Handling: Processes and structures multiple exon/ORF conformations per genetic sequence",
            "Batch Processing: Automatically processes all PDFs in a directory with file-level error logging",
            "Data Validation: Strict character validation for numerical data using valid character whitelist",
            "Structured Output: Generates organized Excel spreadsheets with pandas DataFrame",
            "User Feedback: Color-coded terminal output (green success, red errors, yellow warnings)",
            "Traceability: Preserves original PDF filenames alongside extracted data",
            "Error Resilience: Comprehensive exception handling with detailed error logging to 'errors.txt'",
        ],
    },
    {
        name: "Npm Library: Viewport Detection Hook",
        type: "personal",
        technologies: ["React", "TypeScript", "Custom Hooks", "Intersection Observer API"],
        platforms: ["Web"],
        descriptionLines: [
            "Developers needed an efficient way to trigger actions when components enter the viewport without complex Intersection Observer implementations or external libraries.",
            "Created a lightweight custom React hook that abstracts the Intersection Observer API, providing a simple way to execute callbacks when elements become visible with configurable observation parameters.",
            "Developers import the hook, pass a callback function and optional configuration, then attach the returned ref to any component. The callback triggers automatically when the element enters the viewport according to the specified thresholds.",
        ],
        highlights: [
            "Intersection Observer Abstraction: Simplifies native browser API into a single hook call",
            "Configurable Observation: Supports root element, thresholds, and observation toggling via options",
            "Type-Safe API: Built with TypeScript including VisibleCallbackOptions interface",
            "Performance Optimized: Efficient observation management with automatic cleanup",
            "Flexible Triggering: Callback executes at customizable visibility thresholds (single value or array)",
            "Observation Control: no_observe option to temporarily disable tracking",
            "Simple Integration: Returns a standard ref for seamless component attachment",
            "Zero Dependencies: Pure React implementation without external libraries",
        ],
    },
    {
        name: "Npm Library: PDF Form Filler",
        type: "personal",
        technologies: ["TypeScript", "PDF Form Handling", "Node.js", "PDF-LIB"],
        platforms: ["Node.js"],
        descriptionLines: [
            "Applications needed to programmatically populate PDF forms with structured data, but existing solutions required complex field mapping and manual configuration.",
            "Created an intuitive PDF form filling library that automatically maps JavaScript object properties to PDF form fields using dot-notation, handles nested objects, and provides smart default handling for empty fields.",
            "Developers pass a fields object where keys match PDF field names, and the library automatically populates the template PDF, saves it to the specified output path, and handles all PDF form processing internally.",
        ],
        highlights: [
            "Automatic Field Mapping: Intelligently matches object keys to PDF form field names without manual configuration",
            "Dot-Notation Support: Handles nested objects (e.g., fields.languages.python → 'languages.python' field)",
            "Smart Empty Handling: Automatically fills fields marked with '-' with empty strings",
            "Simple API: Single fillPdf() function with three intuitive parameters",
            "PDF Form Processing: Abstracts PDF form reading, population, and saving",
            "Async Operation: Returns a promise for seamless async/await usage",
            "Template-Based Workflow: Maintains original PDF template while generating filled copies",
            "Type Safety: Designed with TypeScript support for enhanced developer experience",
        ],
    },
    {
        name: "Personal Workout Tracker",
        type: "personal",
        technologies: ["React Native", "Expo", "Context API", "Local Storage", "TypeScript"],
        platforms: ["Android", "iOS"],
        descriptionLines: [
            "My gym's existing workout app was slow, lacked essential features like rest timers, and provided no progress tracking, making it difficult to monitor strength gains and workout consistency.",
            "Developed a custom React Native application featuring workout creation, exercise logging with set/rep/weight tracking, and an integrated rest timer to optimize training sessions and progression monitoring.",
        ],
        highlights: [
            "Workout Creation: Custom routine builder with exercise libraries and personal records",
            "Performance Tracking: Real-time logging of sets, reps, and weights per exercise",
            "Rest Timer: Configurable interval timer between sets/exercises",
            "Offline-First: Local storage ensures functionality without internet connection",
            "Lightweight Design: Optimized performance for low-mid range devices",
            "Intuitive UI: Streamlined interface for quick logging during workouts",
        ],
    },
    {
        name: "Npm Library: Global Confirmation Dialog",
        type: "personal",
        technologies: ["React", "TypeScript", "Context API", "Material-UI", "Custom Hooks"],
        platforms: ["Web"],
        descriptionLines: [
            "Applications needed a consistent, reusable confirmation dialog system that could be triggered from any component without prop drilling or complex state management.",
            "Created a context-based solution with a custom hook that renders Material-UI dialogs globally, allowing developers to trigger confirmation prompts with custom titles, content, and confirmation callbacks through a simple function call.",
            "Developers wrap their app with <ConfirmDialogProvider>, place the <ConfirmDialog> component once, and trigger confirmations from anywhere using confirm({ title, content, onConfirm }) from the useConfirmDialog hook.",
        ],
        highlights: [
            "Global Access: Context-based solution enabling dialog triggers from any component",
            "Simple Implementation: Only requires wrapping app with ConfirmDialogProvider and placing <ConfirmDialog/> once",
            "Customizable API: Pass title, content, and confirmation callback as parameters",
            "Material-UI Integration: Leverages Material-UI's Dialog component for consistent styling",
            "Type-Safe: Built with TypeScript for enhanced developer experience",
            "Callback Control: Executes custom logic only after user confirmation",
            "Clean Architecture: Separates dialog logic from UI components",
            "Lightweight: Minimal bundle size impact with zero dependencies beyond React and Material-UI",
        ],
    },
    {
        name: "Moonlight Idle (RPG Idle Game)",
        type: "personal",
        technologies: ["React Native", "Expo", "Game Development"],
        platforms: ["Android", "iOS"],
        descriptionLines: [
            "Existing mobile idle games lacked depth in character progression, meaningful equipment systems, and engaging combat mechanics.",
            "Developed a feature-rich idle RPG with animated idle combat, deep stats customization, and tower progression system where players challenge their character, equip weapons/accessories, allocate stats, and battle through increasingly difficult tower floors with loot rewards.",
            "Players start in the training section where their character automatically attacks a dummy to gain XP. They can then customize their build through stat allocation (Strength, Dexterity, Stamina) and equipment, and challenge the tower for greater rewards - all with animated combat visuals and sound effects.",
        ],
        highlights: [
            "Idle Combat System: Automated attacks with configurable attack speed (1-5 attacks/sec)",
            "Character Progression: Deep stat system (Strength, Dexterity, Stamina) affecting damage, crit chance, attack speed",
            "Equipment System: weapons/accessories with unique stats (1 weapon + 2 accessories/shields combinations)",
            "Tower Progression: 13 floors with increasingly difficult enemies (unique stats and loot)",
            "Animated Combat: Sprite sheet animations for all characters (idle, attack, death sequences)",
            "Visual Effects: Randomized attack positions/rotations + 3 critical hit animations",
            "Audio Design: Distinct sound effects for regular/critical attacks + ambient music",
            "Offline Progression: Background XP gain when app is closed (reduced rate)",
            "Combat Analytics: Real-time DPS calculation and damage breakdowns",
            "Loot System: Enemy-specific loot tables with item/currency drops",
        ],
    },
    {
        name: "Gym Photo Auto-Uploader",
        type: "personal",
        technologies: ["React Native", "Expo", "Google Auth", "Google Drive API", "Camera API"],
        platforms: ["Android", "iOS"],
        descriptionLines: [
            "My gym required daily photo submissions for content creation, but the manual process of taking photos, renaming files with name/date, and uploading to specific Google Drive folders was time-consuming and repetitive.",
            "Developed a mobile app that automates the entire workflow: authenticates with organization Google accounts, captures photos/videos with configurable aspect ratios, and automatically uploads to designated Drive folders with perfect naming conventions.",
            "After initial Google authentication, users simply open the app, take a photo (or video), and the system automatically saves it to the correct Drive folder with filename format 'Name_YYYY-MM-DD' without any additional steps.",
        ],
        highlights: [
            "Google OAuth Integration: Secure organization-restricted authentication",
            "Automatic Drive Uploads: Seamless Google Drive API integration with folder targeting",
            "Smart Naming: Auto-filename generation using authenticated name + current date",
            "Camera Flexibility: Multiple aspect ratios (1:1, 4:3, 16:9) for content needs",
            "Media Options: Photo capture, selfies, and video recording support",
            "Metadata Handling: Preserves EXIF data with location/time when permitted",
        ],
    },
    {
        name: "CyberPanel Backup Automation System",
        type: "personal",
        technologies: ["Python", "CyberPanel API", "Google Drive API", "MySQL", "Linux Shell", "Cron"],
        platforms: ["Linux Server"],
        descriptionLines: [
            "Our agency needed a reliable solution to automate daily backups of client websites and databases hosted on CyberPanel servers, with secure off-site storage and easy restoration capabilities.",
            "Developed a Python-based system that coordinates CyberPanel backups, compresses website files and database dumps, securely uploads them to Google Drive with date-based organization, and provides one-command restoration.",
            "The system runs daily via cron, automatically backing up all websites and databases. To restore, operators simply run `restore.py domain.com` which downloads the backup from Google Drive and executes CyberPanel's restoration process.",
        ],
        highlights: [
            "Automated Backup Workflow: Single command backs up all websites and databases",
            "Google Drive Integration: Secure OAuth2 authentication with credential persistence",
            "Organized Storage: Daily folders with timestamped backups (YYYY-MM-DD)",
            "Database Handling: mysqldump for all databases with proper credential management",
            "Website Backup: Leverages CyberPanel's native backup commands",
            "Restoration System: One-command download and restoration process",
            "Resource Management: Automatic cleanup of local backup files after upload",
            "Error Handling: Comprehensive exception handling with detailed logging",
            "Security: Encrypted credential storage for Google Drive and MySQL",
            "Cron Integration: Scheduled daily execution without manual intervention",
        ],
    },
    {
        name: "Galaxy Defender (Space Shooter Game)",
        type: "personal",
        technologies: ["Python", "Pygame", "Game Development", "Object-Oriented Programming"],
        platforms: ["Desktop"],
        descriptionLines: [
            "For studying reasons, I wanted to create a modern take on classic space shooters that could run on any desktop system without complex dependencies.",
            "Developed a space shooter using Pygame featuring player ship movement, enemy wave patterns, shooting mechanics, collision detection, increasing difficulty, and full menu systems with pause/restart functionality.",
            "Players control a spaceship using WASD or arrow keys, shoot enemies with spacebar, and survive increasingly difficult waves. The game includes start menus, pause screens, difficulty selection, and game over sequences with score tracking.",
        ],
        highlights: [
            "Space Combat Mechanics: Player ship movement with boundary constraints and shooting system",
            "Dynamic Difficulty: Enemy speed increases with score (0.1 per kill)",
            "Collision System: Precise hit detection using distance-based collision algorithms",
            "Audio Integration: Background music, laser sounds, and explosion effects",
            "UI System: Complete menu system with hover effects, buttons, and text rendering",
            "Game State Management: Start menu, gameplay, pause menu, and game over states",
            "Difficulty Customization: Adjustable number of enemies through menu input",
            "Visual Effects: Sprite rendering with proper positioning and scaling",
            "Restart Functionality: Full game reset with state management",
            "Resolution Independence: Responsive design adapting to different screen sizes",
        ],
    },
    {
        name: "Invoice Automation and Management Platform",
        type: "professional",
        technologies: ["React Native", "Express.js", "MySQL", "FocusNfe API", "Expo"],
        platforms: ["Android", "iOS", "Web"],
        descriptionLines: [
            "Agricultural producers struggled with complex bureaucratic processes for issuing NFP-e tax invoices, requiring physical presence and wasting valuable time that could be spent on farm operations.",
            "Developed a mobile-first solution that enables farmers and accountants to generate legally compliant tax invoices in seconds from any location, with direct integration to Brazil's Federal Revenue systems.",
            "Users authenticate once, then can create, send, and manage agricultural invoices directly from their mobile devices while in the field, at the office, or on-the-go, with all documents automatically stored for compliance.",
        ],
        highlights: [
            "NF-e Generation: Direct integration with Receita Federal for instant invoice validation",
            "Dual User Modes: Separate interfaces for farmers (simple input) and accountants (advanced features)",
            "Location Flexibility: Issue invoices from farm fields without office visits",
            "Compliance Automation: Automatic tax calculations and regulatory updates",
            "Document Management: Cloud storage with organized invoice history",
            "Time Savings: 90% reduction in invoice processing time (avg. 2 min → 10 sec)",
            "Cost Reduction: Eliminates travel costs for invoice processing",
            "Real-Time Sync: Immediate data synchronization between farmers and accountants",
        ],
    },
    {
        name: "Agricultural Spraying Management Platform",
        type: "professional",
        technologies: ["React Native", "Express.js", "MySQL", "Expo", "Geospatial Mapping", "Calendar API"],
        platforms: ["Android", "iOS"],
        descriptionLines: [
            "Farmers lacked efficient tools to manage crop spraying operations, leading to wasted resources, imprecise application, and difficulty coordinating service providers.",
            "Developed a comprehensive agricultural platform featuring plot-based farm management, service request systems, and team coordination tools that optimize spraying operations through precise geospatial mapping and scheduling.",
            "Farmers register their land divided into plots, request spraying services, and track operations in real-time. Service providers use the platform to manage teams, schedules, and resource allocation while administrators monitor overall efficiency.",
        ],
        highlights: [
            "Precision Plot Management: GIS-based plot division and mapping for targeted spraying",
            "Service Marketplace: Connects farmers with spraying service providers",
            "Team Management: Shift scheduling, task assignment, and performance tracking",
            "Calendar Integration: Unified scheduling system for spraying operations",
            "Resource Efficiency: 30% reduction in pesticide/fertilizer usage through precision application",
            "Documentation System: Compliance records for spraying operations",
            "Downtime Reduction: 40% decrease in equipment idle time through optimized scheduling",
        ],
    },
    {
        name: "Professional Haircare Education Platform",
        type: "professional",
        technologies: ["React Native", "Express.js", "MySQL", "Expo", "Content Management System", "Video Streaming"],
        platforms: ["Android", "iOS"],
        descriptionLines: [
            "Haircare professionals lacked centralized access to specialized training for advanced straightening techniques and product knowledge, leading to inconsistent results and missed business opportunities.",
            "Developed an exclusive mobile platform for Loucas & Lisas that provides certified training courses, product tutorials, and community features, enabling stylists to master chemical straightening techniques and stay updated on new formulations.",
            "Beauty professionals use the app to access video courses, earn certifications, discover product usage guidelines, connect with peers, and receive updates on new product launches - all within a branded ecosystem that builds expertise and loyalty.",
        ],
        highlights: [
            "Certification Courses: Step-by-step video training on advanced straightening techniques",
            "Product Knowledge Hub: Detailed formulation information and usage guidelines",
            "Exclusive Content: Early access to product launches and industry trends",
            "Professional Network: Community features for stylist collaboration and knowledge sharing",
            "Offline Access: Download courses for training without internet",
        ],
    },
    {
        name: "Franchise-Localized Educational Toys Marketplace",
        type: "professional",
        technologies: ["React.js", "Node.js", "MySQL", "Geolocation API", "Payment Gateway", "Admin Dashboard"],
        platforms: ["Web (Customer Marketplace)", "Web (Admin Portal)"],
        descriptionLines: [
            "A franchisor of educational toys needed a digital solution that respected territorial franchise agreements while offering a unified shopping experience, preventing cross-franchise sales conflicts that could violate franchisee territories.",
            "Developed a dual-platform system with: 1) A customer marketplace that automatically selects the appropriate franchise (or headquarters) based on user location (GPS/ZIP), dynamically adjusting products, prices and coupons; 2) An admin portal for franchise management, user promotions, and sales analytics.",
            "Customers shop through a territory-aware interface while franchisor administrators use the dedicated portal to promote users to franchisees (granting wholesale access), analyze sales by franchise, create coupons, update banners, and monitor all marketplace activity.",
        ],
        highlights: [
            "Automatic Territory Mapping: GPS/ZIP-based franchise selection preventing cross-territory sales",
            "Dynamic Pricing & Inventory: Franchise-specific products, prices, and coupons displayed based on location",
            "Sales Analytics: Franchise-specific performance dashboards",
            "Centralized Control: Banner management, coupon creation, order oversight",
            "Geofencing Technology: Strict enforcement of franchise sales territories",
            "Inventory Synchronization: Real-time stock updates across franchise locations",
        ],
    },
    {
        name: "QR-Powered In-Store Shopping",
        type: "professional",
        technologies: ["React Native", "QR Code", "Payments Gateway", "Real-time Inventory API"],
        platforms: ["Android", "iOS"],
        descriptionLines: [
            "Developed a mobile app that transforms physical stores into seamless self-service environments using QR code scanning technology, allowing customers to scan products, build carts, and checkout digitally without visiting a cashier.",
            "Shoppers scan QR codes on product displays to add items to their digital cart, apply discounts, and complete purchases directly through the app - eliminating checkout lines while providing real-time inventory visibility and personalized offers.",
        ],
        highlights: [
            "QR Code Product Scanning: Instant addition to cart via QR codes on shelves",
            "Frictionless Checkout: In-app payment processing with saved payment methods",
            "Real-time Inventory Sync: Live stock levels and location-based product availability",
            "Digital Receipts: Automatic email/SMS receipts with purchase details",
            "Personalized Offers: Location-based promotions triggered by store beacons",
            "Shopping List Integration: Pre-build lists that guide in-store navigation",
            "Supplement Information: Detailed product specs and usage guidelines",
            "Time Savings: 75% reduction in checkout time (avg. 8 min → 2 min)",
        ],
    },
    {
        name: "Event Engagement Wheel",
        type: "professional",
        technologies: ["React.js", "Express.js", "MySQL", "QR Code", "CRM Integration"],
        platforms: ["Web"],
        descriptionLines: [
            "A customer needed an interactive way to engage visitors at Oktoberfest Curitiba 2023 that would promote their German breads while capturing customer information for future marketing.",
            "Developed a spinning wheel app activated by QR codes at the event booth, allowing participants to register and spin for instant prizes, creating excitement while building a qualified lead database.",
            "Event attendees scanned booth QR codes to access the app, registered with their contact information, spun the digital wheel for immediate rewards, and became part of the customer's marketing ecosystem for future promotions.",
        ],
        highlights: [
            "QR Code Activation: Instant app access via booth QR codes",
            "Spinning Wheel Interface: Interactive prize wheel with physics-based animation",
            "Lead Generation: Custom registration form capturing name/email/contact",
            "Instant Rewards: Digital coupons and physical prizes distribution",
            "CRM Integration: Automatic lead syncing to marketing databases",
            "Prize Management: Configurable prize distribution probabilities",
        ],
    },
    {
        name: "Interactive Coloring Game",
        type: "professional",
        technologies: ["React Native", "Canvas API", "Touch Gestures", "Social Sharing", "Child-Friendly UI"],
        platforms: ["Android", "iOS"],
        descriptionLines: [
            "Our customer wanted engaging digital tools that combined creative expression with familiar characters from it's educational toys and universe.",
            "Developed an intuitive coloring app featuring characters from ou customer's toy line, with color blending effects, and one-tap sharing to encourage artistic expression and storytelling.",
            "Children select characters from the our customer universe, paint using finger gestures with realistic brush effects, save their creations to a digital gallery, and easily share artwork with family - all within a child-safe interface with no external links or ads.",
        ],
        highlights: [
            "Character Gallery: 10+ coloring pages featuring our customer's popular toy characters",
            "Child-Safe Interface: Rounded corners, large buttons, and intuitive gestures designed for small hands",
            "Creative Tools: Color palette with 30+ hues, adjustable brush sizes, and undo/redo functionality",
            "Art Gallery: Automatic saving of creations with thumbnail previews",
            "Sharing: One-tap sharing social apps",
            "Offline Functionality: Full painting capability without internet connection",
        ],
    },
    {
        name: "Educational Memory Game",
        type: "professional",
        technologies: ["React Native", "Child-Friendly UI"],
        platforms: ["Android", "iOS"],
        descriptionLines: [
            "Our customer wanted engaging cognitive development tools that incorporated familiar characters from it's educational toys and universe.",
            "Developed a themed memory matching game featuring our customer's iconic characters with timed challenges, and cognitive tracking to enhance memory skills while maintaining brand engagement.",
            "Children play by matching character pairs against the clock, progressing through levels that track their memory development, with educators and parents able to monitor cognitive improvement through gameplay statistics.",
        ],
        highlights: [
            "Character Integration: Features brand characters as matching cards with unique animations",
            "Timed Challenges: Single gameplay mode with countdown timer for repeated play",
            "Cognitive Tracking: Records accuracy percentage and average match time per session",
            "Simple Gameplay: Single consistent challenge format for all players",
            "Brand Alignment: Complete customization with client's characters",
        ],
    },
    {
        name: "Easter Hidden Object Game",
        type: "professional",
        technologies: ["React Native", "Object Oriented Programming"],
        platforms: ["Android", "iOS"],
        descriptionLines: [
            "Our customer wanted engaging visual perception activities during the Easter season that combined holiday fun with cognitive development, beyond traditional egg hunts.",
            "Developed a themed hidden object game featuring vibrant Easter scenes with progressively challenging levels that train attention to detail, pattern recognition, and visual processing speed through time-based object finding challenges.",
            "Players explore detailed Easter environments (gardens, bunny workshops, spring forests) to find cleverly hidden objects against the clock, with educators and parents able to track visual perception improvements through gameplay analytics.",
        ],
        highlights: [
            "Three themed environments: Easter Garden (morning), Bunny Workshop (afternoon), and Spring Forest (evening)",
            "Seasonal background music creating holiday atmosphere",
            "Procedural generation of props and objects",
            "Collision detection and realocation",
        ],
    },
    {
        name: "Multiplayer Wordle Game",
        type: "personal",
        technologies: ["React.js", "Express.js", "Socket.IO", "Real-time Multiplayer"],
        platforms: ["Web"],
        descriptionLines: [
            "I wanted a competitive multiplayer version of the popular word game with adjustable difficulty and private rooms for friends, but existing solutions lacked these social and customization features.",
            "Developed a real-time multiplayer Wordle clone with customizable word lengths (5-9 letters), private rooms with password protection, and a skill-based scoring system that rewards efficient guessing.",
            "Players create rooms with custom nicknames, set word length and privacy options, then compete to guess the target word in the fewest attempts. The faster a player guesses correctly, the more points they earn in the real-time leaderboard.",
        ],
        highlights: [
            "Adjustable Difficulty: Players choose word length from 5 to 9 letters",
            "Multiplayer Rooms: Create public or password-protected private rooms",
            "Real-time Gameplay: Synchronized word guessing via Socket.IO",
            "Scoring System: Points awarded based on number of attempts (fewer attempts = higher score)",
            "Word Validation: Integration with dictionary API for legitimate words",
            "Nickname System: Custom player identifiers with avatar support",
            "Leaderboard Tracking: Real-time score comparison during gameplay",
            "Turn-Based Mechanics: Sequential guessing with immediate feedback",
            "Color-Coded Feedback: Standard Wordle letter coloring (green/yellow/gray)",
            "Room Persistence: Games maintain state even if players disconnect",
            "Attempt Counter: Visual display of remaining guesses",
            "Minimalist Interface: Clean Wordle-inspired UI with focus on gameplay",
        ],
    },
    {
        name: "Professional Teleprompter App",
        type: "professional",
        technologies: ["React Native", "Expo Camera"],
        platforms: ["Android", "iOS"],
        descriptionLines: [
            "Content creators needed professional teleprompter functionality to deliver natural on-camera performances without memorizing scripts, but existing solutions were either too expensive or lacked mobile-friendly features.",
            "Developed a mobile teleprompter app that displays customizable scrolling scripts during video recording, with precise speed control, text positioning, and visual enhancements to create natural eye contact and fluent delivery.",
            "Users input scripts, adjust scrolling speed and text appearance, then record videos while reading the auto-scrolling text - eliminating memorization needs and creating professional-quality videos directly from mobile devices.",
        ],
        highlights: [
            "Script Visualization: Real-time scrolling text overlay during recording",
            "Speed Control: Precise adjustment from 10-100 words per minute",
            "Text Customization: Adjustable font size (12-36pt), color schemes, and opacity",
            "Positioning Options: Vertical text placement for optimal eye line",
        ],
    },
    {
        name: "All-in-One Agency Management Platform",
        type: "professional",
        technologies: ["React.js", "Express.js", "MySQL", "Socket.IO", "Electron"],
        platforms: ["Web", "Desktop"],
        descriptionLines: [
            "Our agency needed a unified solution for employee time tracking, client management, and productivity tools - replacing multiple disconnected systems with manual processes and inconsistent data.",
            "Developed a comprehensive management platform combining time tracking (clock-in/out, breaks), client/project management, announcement broadcasting, and utility tools (QR generator, API tester, coffee roulette) in a single integrated system.",
            "Employees clock in/out via login, track project time, manage client information, receive announcements, while managers monitor productivity, generate reports, and use specialized tools - all within one centralized platform.",
        ],
        highlights: [
            "Time Tracking: Login-based clock-in/out system with lunch/pause logging",
            "Centralized Announcements: Company-wide notification broadcasting",
            "Client Management: Unified client database with contact/project history",
            "Project Time Tracking: Automatic time logging per project/client",
            "QR Generator: Customizable QR code creation for URLs/contacts/wi-fi",
            "API Testing Suite: Save/manage HTTP requests and WebSocket events",
            "Coffee Roulette: Fun employee rotation system for coffee duty",
            "Productivity Reports: Time utilization analytics per project/client",
            "Break Management: Track and regulate pause/lunch durations",
            "Overtime Monitoring: Automatic overtime calculation and alerts",
            "Socket.IO Integration: Real-time team notifications and updates",
            "Role-Based Access: Custom permissions for employees/managers/admins",
            "Dashboard Analytics: Visual metrics for time allocation and productivity",
        ],
    },
    {
        name: "White-Label PagSeguro Gateway",
        type: "professional",
        technologies: ["React.js", "Express.js", "PagSeguro API", "Socket.io", "Payment Processing"],
        platforms: ["React.js Component", "Web"],
        descriptionLines: [
            "E-commerce stores needed seamless PagSeguro integration with custom branding that matched their agency's identity, but implementing payment gateways required complex technical setup and lacked visual consistency.",
            "Developed a white-label payment gateway solution where stores simply register their PagSeguro tokens and unique name to automatically enable branded checkout flows with PIX, boleto, credit/debit cards, installments, and shipping calculations.",
            "E-commerces use either the React component for custom stores or WordPress redirect solution for simpler implementations - both providing a unified branded experience while handling all payment processing through their own PagSeguro accounts.",
        ],
        highlights: [
            "White-Label Solution: Fully branded checkout matching agency visual identity",
            "Simplified Setup: Store onboarding with just PagSeguro tokens and unique name",
            "Payment Options: PIX, boleto, credit/debit cards with installment plans",
            "Shipping Integration: Real-time freight calculation (optional/included)",
            "React Component: Drop-in payment UI for React-based e-commerce",
            "WordPress Redirect: Simple integration for WordPress stores",
            "Installment Engine: Customizable installment rules (1-12 months)",
            "Automatic Webhooks: Payment status notifications to merchant systems",
            "Unified Dashboard: Consolidated view across all merchant accounts",
            "Security Compliance: PCI-DSS Level 1 certified processing",
            "Brand Consistency: Agency's visual identity applied to all checkouts",
            "Multi-merchant Support: Single gateway serving multiple stores",
            "Real-time Analytics: Payment success/failure tracking",
        ],
    },
    {
        name: "Medical Leave Certificate Automation System",
        type: "professional",
        technologies: ["Python", "MySQL", "Web Services", "RPA"],
        platforms: ["Backend System"],
        descriptionLines: [
            "HR departments struggled with manual processing of medical leave certificates, requiring time-consuming verification of employee data, consultation types, and medical codes to determine absence eligibility.",
            "Developed an automated processing system that ingests OCR-extracted medical certificates, validates them against employee records, determines consultation type (teleconsultation vs. in-person) through address verification, and applies CID-based business rules to approve/reject leave requests.",
            "The system continuously monitors the database for new certificates, processes each record through validation rules, and automatically updates the absence tracking system with approval decisions - eliminating manual verification while ensuring compliance with medical leave policies.",
        ],
        highlights: [
            "OCR Integration: Processed structured data from OCR outputs of medical certificates",
            "Address Verification System: Compared employee addresses with consultation locations to determine teleconsultation eligibility",
            "CID-Based Rules Engine: Implemented medical code (CID) validation for automatic leave approval/rejection",
            "Employee Data Cross-Referencing: Integrated with HR databases to validate employee information",
            "Automated Decision Making: Determined absence eligibility without human intervention",
            "Database Synchronization: Maintained processed records in dedicated MySQL tables",
            "Audit Trail: Created comprehensive logging of processing decisions",
            "Exception Handling: Managed incomplete/invalid certificates with alerting system",
            "Compliance Assurance: Enforced company medical leave policies through configurable rules",
        ],
    },
    {
        name: "Grim Fight, a Roguelite Autobattler or Auto Chess game",
        type: "personal",
        technologies: ["Phaser.js", "React.js", "Electron", "MUI", "Electron"],
        platforms: ["Web", "Desktop (Electron)"],
        descriptionLines: [
            "A snappy roguelite auto-battler with drag-and-drop squad building, crunchy item crafting, and flashy abilities.",
            "Build a team, place them on a tactical grid, hit Space, and watch AI-driven chaos with milestone augments, TFT-style recipes, and trait synergies that reward smart roster building.",
            "Infinite, seed-based procedural floors: the same shared seed guarantees identical floors for everyone, with no hand-scripted layouts. Every 10th floor is a boss fight.",
        ],
        highlights: [
            "Tactical Auto-Battles: Grid placement, items, and synergies determine the fight. Units handle the rest automatically",
            "Trait Synergy System: Each unit has 1–3 traits (e.g., Vampire, Assassin, Frostborn, Guardian, Scholar). Bonuses activate based on UNIQUE units with that trait on board (bench doesn’t count, duplicates don’t stack). Typical breakpoints: 2/4/6 or 3/5/7, scaling teamwide buffs (e.g., lifesteal, crit chance/damage, chill/slow → freeze, start-of-round shielding, mana/ability haste). Units contribute to all their traits simultaneously, allowing cross-trait builds",
            "Item Crafting: 2-by-2 component fusion with auto-merge on valid pairs (e.g., Sword+Sword→Berserker Blade; Sword+Tear→Focus Edge; Rod+Rod→Arcane Crown; Gloves+Gloves→Trickster’s Gloves)",
            "Augments & Events: Draft augments every few floors; enemies gain augments at milestones to keep runs fresh",
            "Procedural Floors (Seeded & Deterministic): A single shared seed drives generation so every player faces the same sequence. No floor is hand-authored; content is fully algorithmic",
            "Encounter Generator & CR Budgeting: Each floor targets a Challenge Rating (CR). The generator selects enemy packs with known CR values and scales their tiers/quantities to hit the budget, clamping extremes to keep fights fair and varied",
            "Boss Cadence: Every 10th floor rolls a boss encounter from the seed with scaled stats and reward tiers, acting as difficulty checkpoints",
            "Scaling Curves: Health/damage and gold/loot rewards scale with floor depth; elite variants adjust effective CR to maintain threat without spammy unit counts",
            "Abilities With Style: Dracula’s blood hunt, Rogue’s blink-flurry, Ymir’s freezing nova—each unit has a defining kit",
            "Roguelite Loop: 3 lives, escalating floors, gold rewards, occasional loot drops, and local run records",
            "Satisfying Juice: Damage numbers, glow/border highlights, blood bursts, lighting, smooth tweened movement",
            "Event Bridge: Lightweight EventBus syncing Phaser game state with React UI (shop, augments, inventory)",
        ],
    },
    {
        name: "Forro Cwb (Dance Events Hub)",
        type: "personal",
        technologies: ["TypeScript", "React.js", "Express.js", "MySQL", "Google Maps"],
        platforms: ["Web"],
        descriptionLines: [
            "Forro Cwb centralizes Forró events in the city for the dance community.",
            "An admin dashboard lets organizers register artists, bands, and events with images, venue (Google Maps), prices and ticket links, schedules, and more.",
            "The main user view shows a week-by-week event board with 7 clean columns (one per weekday) and navigation for previous/next week to quickly find the right party.",
        ],
        highlights: [
            "Admin Dashboard: CRUD for artists, bands, and events with image uploads",
            "Location Integration: Venue selection and display via Google Maps",
            "Ticketing & Pricing: Add prices and external ticket purchase links",
            "Scheduling: Manage times and complete event details",
            "Event Analytics: Charts showing occurrences by artist/band across events",
            "Weekly Calendar UI: 7-column layout with next/previous week navigation",
            "User-Friendly Browsing: Quickly find events with all key info at a glance",
        ],
    },
    {
        name: "Lead-to-CRM-to-Invoice Automation (RD Station ↔ Vhsys)",
        type: "professional",
        technologies: ["TypeScript", "Express.js", "RD Station API", "Vhsys API", "Webhooks"],
        platforms: ["Backend Service"],
        descriptionLines: [
            "Automates the entire path from website budget request → CRM deal → invoicing system, eliminating double data entry.",
            "API receives the site form, upserts the contact in RD Station, creates a sales funnel's deal with the chosen products, and tracks its progress.",
            "When the deal reaches the final stage (via webhook), the service creates the customer in Vhsys and hands off billing/financial workflows.",
        ],
        highlights: [
            "Form Intake: Validates and normalizes website submissions; associates product line items with the prospect",
            "RD Station Sync: Upserts contact, opens a deal in the selected funnel, and attaches products/notes to the opportunity",
            "Stage Webhook: Listens for deal moved to the final stage; verifies signature, fetches contact, and triggers downstream actions",
            "Vhsys Handoff: Creates/updates the customer record in Vhsys to start invoicing and financial processes",
            "Idempotency & Retries: Request keys and replay-safe processing prevent duplicates across API and webhook flows",
            "Product Mapping: Catalog mapping ensures product codes/descriptions stay consistent between website, RD Station, and Vhsys",
            "Security & Compliance: Scoped API tokens, secret management, and data minimization aligned with LGPD best practices",
        ],
    },
    {
        name: "Planika (Collaborative Trip Planner)",
        type: "personal",
        technologies: ["TypeScript", "React.js", "Express.js", "MySQL", "Hocuspocus.js"],
        platforms: ["Web"],
        descriptionLines: [
            "Planning group trips required juggling spreadsheets, messaging apps, and scattered notes, making it difficult to track expenses, assign responsibilities, and maintain a clear budget overview across multiple travelers.",
            "Developed a real-time collaborative trip planning platform featuring hierarchical budget organization, dynamic filtering, and simultaneous editing that enables travel groups to plan, track, and manage trip expenses together seamlessly.",
            "Travel groups invite companions via email, organize expenses in an interactive tree structure, filter by location/traveler/date/status, track who's booking what, and monitor costs in real-time as everyone collaborates on the trip budget.",
        ],
        highlights: [
            "Interactive Tree Structure: Hierarchical budget organization showing total costs for each expense branch",
            "Dynamic Filtering: Click any location, traveler, date, or reservation status to interactively filter the entire trip view",
            "Real-Time Collaboration: Invite travel companions by email and see instant updates as everyone adds expenses and comments simultaneously",
            "Timeline Planning: Schedule expenses across trip dates, identify high-spend days, and track itinerary costs chronologically",
            "Status Tracking: Mark items as pending, reserved, or paid; assign booking responsibilities to clarify who handles what",
            "Location-Based Organization: Group expenses by destination and track spending patterns across trip locations",
            "Reports Generation: Generate detailed expense reports by location and export in popular formats or email",
            "Collaborative Updates: Hocuspocus.js-powered live synchronization for seamless multi-user editing",
            "Google Authentication: Secure sign-in and user management for travel group coordination",
            "Visual Cost Breakdown: Interactive expense visualization showing daily, weekly, and location-based spending",
            "Responsibility Assignment: Clear accountability with named booking assignments per expense item",
            "Expense Categories: Organize costs hierarchically (flights, accommodations, activities, meals, transportation)",
        ],
    },
]

export const Projects: React.FC<ProjectsProps> = (_) => {
    return (
        <SectionWrapper title="Projects">
            {projects.map((project) => (
                <Project key={project.name} {...project} />
            ))}
        </SectionWrapper>
    )
}
